# we use this file to run our containers
version: '3'

services:
  app:
    image: shadi38/node-app:4.0
    container_name: nice_williamson
    restart: always
    ports:
    #we map the host(my laptop) port to the container port -- host:container
      - "3000:3000"
    #when I visit http://localhost:3000, the request goes to:
    # Host port 3000
    #Docker forwards it to container port 3000