# we use this file to run our containers
version: '3'

services:
  app:
    image: shadi38/node-app:4.0
    container_name: nice_williamson
    restart: always
    ports:
    #we map the container port to the host port -- host:container
      - "3000:3000"
    